language: shell
os: linux
services: docker
dist: bionic

env:
  global:
    IMAGE: quay.io/konveyor/oadp-operator
    DEFAULT_BRANCH: master
    DOCKERFILE: Dockerfile
before_install:
  - set -e
  - export TAG="${TRAVIS_BRANCH}"
  - if [ "${TRAVIS_BRANCH}" == "${DEFAULT_BRANCH}" ]; then export TAG=latest; fi
jobs:
  include:
  - stage: build image
    arch ppc64le
    script:
    - docker build -t ${IMAGE}:${TAG}-${TRAVIS_ARCH} -f ${DOCKERFILE} .
    - if [ -n "${QUAY_ROBOT}" ]; then docker login quay.io -u "${QUAY_ROBOT}" -p ${QUAY_TOKEN}; fi
    - if [ -n "${QUAY_ROBOT}" ]; then docker push ${IMAGE}:${TAG}-${TRAVIS_ARCH}; fi
