language: shell
os: linux
services: docker
dist: bionic

env:
  global:
    IMAGE: quay.io/jmontleon/travis-multiarch-test
    DEFAULT_BRANCH: main
    DOCKERFILE: Dockerfile
jobs:
  include:
   - stage: build image
     arch: ppc64le
     script:
     - docker build -t ${IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_CPU_ARCH} -f ${DOCKERFILE} .
     - ./.travis-push-image.sh
   - arch: amd64
     script:
     - docker build -t ${IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_CPU_ARCH} -f ${DOCKERFILE} .
     - ./.travis-push-image.sh
   - arch: s390x
     script:
     - docker build -t ${IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_CPU_ARCH} -f ${DOCKERFILE} .
     - ./.travis-push-image.sh
   - arch: arm64
     script:
     - docker build -t ${IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_CPU_ARCH} -f ${DOCKERFILE} .
     - ./.travis-push-image.sh
   - stage: push manifest
     arch: amd64
     script: ./.travis-push-manifest.sh
