language: shell
os: linux
services: docker
dist: bionic

env:
  global:
    IMAGE: quay.io/jmontleon/travis-multiarch-test
    DEFAULT_BRANCH: main
    DOCKERFILE: Dockerfile
jobs:
  include:
   - stage: build image
     arch: ppc64le
     script:
     - ./.travis-build-image.sh
     - docker build -t ${IMAGE}:${TAG}-${ARCH} -f ${DOCKERFILE}
     - bash -c "if [[ -n \"${QUAY_ROBOT}\" ]]; then docker push ${IMAGE}:${TAG}-${ARCH}; fi"
   - arch: amd64
     script:
     - ./.travis-build-image.sh
     - docker build -t ${IMAGE}:${TAG}-${ARCH} -f ${DOCKERFILE}
     - bash -c "if [[ -n \"${QUAY_ROBOT}\" ]]; then docker push ${IMAGE}:${TAG}-${ARCH}; fi"
   - arch: s390x
     script:
     - ./.travis-build-image.sh
     - docker build -t ${IMAGE}:${TAG}-${ARCH} -f ${DOCKERFILE}
     - bash -c "if [[ -n \"${QUAY_ROBOT}\" ]]; then docker push ${IMAGE}:${TAG}-${ARCH}; fi"
   - arch: arm64
     script:
     - ./.travis-build-image.sh
     - docker build -t ${IMAGE}:${TAG}-${ARCH} -f ${DOCKERFILE}
     - bash -c "if [[ -n \"${QUAY_ROBOT}\" ]]; then docker push ${IMAGE}:${TAG}-${ARCH}; fi"
   - stage: push manifest
     arch: amd64
     script: ./.travis-push-manifest.sh
